name: "Smart Release Please"
description: "Handles RC calculation on next and Stable promotion on main."

inputs:
  token:
    description: "GitHub Token (PAT)"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6 
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Check if should skip
      id: skip_check
      shell: bash
      run: |
        COMMIT_MSG="${{ github.event.head_commit.message }}"
        
        # Always skip release merge commits
        if [[ "$COMMIT_MSG" == "chore(main): release"* ]] || \
           [[ "$COMMIT_MSG" == "chore(next): release"* ]] || \
           [[ "$COMMIT_MSG" == "chore: release"* ]]; then
          echo "Release merge commit detected - skipping"
          echo "skip=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Skip bot maintenance commits ONLY if they already have [skip ci]
        # This prevents the second trigger but allows the first one
        if [[ "$COMMIT_MSG" == *"[skip ci]"* ]]; then
          echo "Skip CI tag detected - skipping"
          echo "skip=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "Proceeding with workflow"
        echo "skip=false" >> $GITHUB_OUTPUT

    - name: Set up Python
      if: steps.skip_check.outputs.skip != 'true'
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Calculate Correct RC Version
      if: steps.skip_check.outputs.skip != 'true'
      id: calc_rc
      shell: bash
      run: python3 "${{ github.action_path }}/rc_align.py"

    - name: Fix Manifest for Main Branch
      if: steps.skip_check.outputs.skip != 'true' && (github.ref_name == 'main' || github.ref_name == 'master')
      shell: bash
      run: |
        git config user.name "mapcolonies[bot]"
        git config user.email "devops[bot]@mapcolonies.com"
        
        # On main, find the last stable release and update manifest
        LAST_STABLE=$(git tag -l "v[0-9]*.[0-9]*.[0-9]" --sort=-creatordate | head -n1 | sed 's/^v//')
        
        CURRENT_MANIFEST=$(cat .release-please-manifest.json 2>/dev/null || echo '{}')
        
        if [ -n "$LAST_STABLE" ]; then
          echo "Setting manifest to last stable release: $LAST_STABLE"
          NEW_MANIFEST="{\".\": \"$LAST_STABLE\"}"
        else
          echo "No stable release found, using calculated version"
          TARGET_VER="${{ steps.calc_rc.outputs.next_version }}"
          NEW_MANIFEST="{\".\": \"$TARGET_VER\"}"
        fi
        
        # Check if manifest actually needs updating
        if [[ "$CURRENT_MANIFEST" != "$NEW_MANIFEST" ]]; then
          echo "$NEW_MANIFEST" > .release-please-manifest.json
          git add .release-please-manifest.json
          git commit -m "chore: reset manifest to stable version [skip ci]"
          git push "https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git" ${{ github.ref_name }}
          echo "Manifest updated and pushed"
        else
          echo "Manifest already correct, no changes needed"
        fi

    - name: Inject Release-As Footer
      if: >-
        ${{ 
          steps.skip_check.outputs.skip != 'true' &&
          steps.calc_rc.outputs.next_version != '' &&
          !contains(github.event.head_commit.message, 'Release-As:')
        }}
      shell: bash
      run: |
        git config user.name "mapcolonies[bot]"
        git config user.email "devops[bot]@mapcolonies.com"

        TARGET_VER="${{ steps.calc_rc.outputs.next_version }}"
        LAST_MSG=$(git log -1 --pretty=%B)
        
        # Double-check footer doesn't exist
        if [[ "$LAST_MSG" == *"Release-As: $TARGET_VER"* ]]; then
          echo "Footer already present. Skipping."
          exit 0
        fi

        # Commit with [skip ci] to prevent re-triggering
        git commit --allow-empty -m "chore: enforce correct rc version [skip ci]" -m "Release-As: $TARGET_VER"
        git push "https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git" ${{ github.ref_name }}
        echo "Version footer injected"

    - name: Close Stale Release PRs
      if: steps.skip_check.outputs.skip != 'true' && !contains(github.ref, 'release-please--branches')
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        echo "Checking for stale release PRs on ${{ github.ref_name }}..."
        
        PR_DATA=$(gh pr list \
          --base "${{ github.ref_name }}" \
          --label "autorelease: pending" \
          --json number,state \
          --jq '.[0]')

        if [ -n "$PR_DATA" ] && [ "$PR_DATA" != "null" ]; then
          PR_NUMBER=$(echo "$PR_DATA" | jq -r '.number')
          PR_STATE=$(echo "$PR_DATA" | jq -r '.state')
          
          if [ "$PR_STATE" == "OPEN" ]; then
            echo "Closing stale PR #$PR_NUMBER..."
            gh pr close "$PR_NUMBER" --delete-branch
          fi
        else
          echo "No stale PRs found"
        fi

    - name: Run release-please
      if: steps.skip_check.outputs.skip != 'true'
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        target-branch: ${{ github.ref_name }}
        config-file: release-please-config.${{ github.ref_name }}.json
